[pytest]
asyncio_mode = auto
pythonpath = .
testpaths = tests
addopts = --cov=app.routers --cov=app.services --cov=app.repositories --cov=app.utils --cov=app.validators --cov=app.main --cov-report=term-missing
