package com.example.SpringCoreAssignment.component;

import org.springframework.stereotype.Component;

@Component
public class LongMessageFormatter implements MessageFormatter {

    public String format() {
        return "This is a long formatted message generated by the system.";
    }
}
