from enum import Enum

# Enum for candidate status
class CandidateStatus(str, Enum):
    PROFILE_CREATED = "PROFILE_CREATED"
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
    INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED"
    SELECTED = "SELECTED"
    REJECTED = "REJECTED"
