spring.application.name=SpringAdvanceAssignment

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/SpringAdvanceAssignment
spring.datasource.username=postgres 
spring.datasource.password=2004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true 